name = "glychee"
version = "0.2.7"
licences = ["Apache-2.0"]
description = "Glychee: Easy access to Elixir's Benchee from Gleam!"
repository = { type = "github", user = "inoas", repo = "glychee" }
# links = [{ title = "Website", href = "https://gleam.run" }]
target = "erlang"

[dependencies]
benchee = "~> 1.1"

[documentation]
pages = [
	{ title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
	{ title = "LICENSE", path = "license.html", source = "LICENSE" },
]
