name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: erlef/setup-beam@v1.13.0
        with:
          otp-version: "25.1"
          gleam-version: "0.0.0-nightly-221019"
          # elixir-version: "1.14.1"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
